//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempSuitability_CSharp {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class TS_Model_Run_Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static TS_Model_Run_Settings defaultInstance = ((TS_Model_Run_Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new TS_Model_Run_Settings())));
        
        public static TS_Model_Run_Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/home/harry/tsmodel/data_5km/LST_Day_5km_8day/*.tif")]
        public string LST_Day_Files {
            get {
                return ((string)(this["LST_Day_Files"]));
            }
            set {
                this["LST_Day_Files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/home/harry/tsmodel/data_5km/LST_Night_5km_8day/*.tif")]
        public string LST_Night_Files {
            get {
                return ((string)(this["LST_Night_Files"]));
            }
            set {
                this["LST_Night_Files"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/home/harry/tsmodel/data_5km/out")]
        public string OutputFolder {
            get {
                return ((string)(this["OutputFolder"]));
            }
            set {
                this["OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-18")]
        public double WestLim {
            get {
                return ((double)(this["WestLim"]));
            }
            set {
                this["WestLim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public double EastLim {
            get {
                return ((double)(this["EastLim"]));
            }
            set {
                this["EastLim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public double NorthLim {
            get {
                return ((double)(this["NorthLim"]));
            }
            set {
                this["NorthLim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-35")]
        public double SouthLim {
            get {
                return ((double)(this["SouthLim"]));
            }
            set {
                this["SouthLim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/home/harry/tsmodel/data_5km/CoastGlobal_5k.tif")]
        public string LS_Mask_File {
            get {
                return ((string)(this["LS_Mask_File"]));
            }
            set {
                this["LS_Mask_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public ushort MaskValidValue {
            get {
                return ((ushort)(this["MaskValidValue"]));
            }
            set {
                this["MaskValidValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("512")]
        public uint TileSizePx {
            get {
                return ((uint)(this["TileSizePx"]));
            }
            set {
                this["TileSizePx"] = value;
            }
        }
    }
}
